[package]
name = "udpexposer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
argh = "0.1.13"
lru = "0.12.5"
tokio = { version = "1.42.0", features = ["net", "rt", "macros", "time", "io-util", "sync"] }
